// Mocks generated by Mockito 5.4.4 from annotations
// in kro_trust_task/test/modules/transaction_history/data/datasources/transaction_history_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kro_trust_task/modules/transaction_history/data/datasources/transaction_history_datasource.dart'
    as _i3;
import 'package:kro_trust_task/modules/transaction_history/data/models/transactions.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransaction_0 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionHistoryDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionHistoryDatasource extends _i1.Mock
    implements _i3.TransactionHistoryDatasource {
  @override
  _i4.Future<_i2.Transaction> getTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
        ),
        returnValue: _i4.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #getTransactions,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #getTransactions,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Transaction>);
}
